on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@latest
      - name: Build APK
        uses: digreatbrian/buildozer-action@latest
        with:
          python-version: 3.12
          buildozer-cmd: buildozer -v android debug

      - name: Upload artifacts
        uses: actions/upload-artifact@latest
        with:
          name: package
          path: ./bin/*.apk
